POST http://127.0.0.1:5000/api/create/patient/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMzM0MzA3NiwianRpIjoiZDI4YTRjYTktNmQ0MS00YTc5LWI4NzItMGJkZDA4Y2UzNjlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNzEzMzQzMDc2LCJjc3JmIjoiYjI2OTk2MTgtYmQyMS00ZWRiLWJjY2YtYmI3OTE0YzgxMGQyIiwiZXhwIjoxNzEzMzQzOTc2fQ.HZW5uahHgVrA3d7ITDAabFM4_m44zM0Rt9LM2Va_mKQ

{
    "email": "patient@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "phone": "123-456-7890"
}



